name: udemy_flutter_mvvm
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  analyzer: ^5.12.0
  carousel_slider: ^4.2.1
  connectivity_plus: ^4.0.0
  country_code_picker: ^3.0.0
  dartz: ^0.10.1
  device_info_plus: ^9.0.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  logger: ^1.3.0
  lottie: ^2.4.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.6.2
  retrofit_generator: ^7.0.0
  freezed: ^2.3.4

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/json/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
